name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - "packages/container/**"

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://mfs-project-dashboard/container/latest
        env:
          AWS_ACCESS_KEY_ID: AKIAVVZPCI243CW4W2C3
          AWS_SECRET_ACCESS_KEY: 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
          AWS_DEFAULT_REGION: us-east-2
